Miwashotaro patch 1
iaeste-japan/www pull request #36
Opened 2023-07-10 02:38 UTC by Miwashotaro

山元様

お世話になっております。
HPの更新が遅くなり、申し訳ありませんでした。
更新が終わりました。
以下は更新箇所です。

static/files/intership/information-session
インターシップ説明会の2023年度の資料をアップロードしました。

content/ja/information-session.md
2023年度のインターシップの説明会の日程を掲載しました。
説明会の資料を2023年のものに更新し、参加方法をtwitterに変更しました。

content/ja/ how-it-works.md
各種費用のIAESTE Japanへの納入額の項で
情報を更新しました。

static/files/intership/ required-docs
2024年度版の募集要項、研修の手引き、申請書、派遣辞退届を日本語版、英語版併せて
7件、ここにアップロードしました。

content/ja/required-docs.md
エントリーフォームのドキュメント一覧から追加募集要項を削除しました。
募集要項、研修の手引き、申請書のファイルを2024年度版に更新しました。
日本語版と英語版で上記の作業を行いました。
日本語版のドキュメント一覧で新たに
派遣辞退届のファイルを追加しました。

static/files/intership/ reports
ここに派遣研修生報告書、2022年度版8件をアップロードしました。

content/ja/reports.md
派遣生研修報告書の表に2022年度の報告書を8件、表の上に追加しました。

以上となります。
確認と修正をよろしくお願いいたします。

IAESTE学生委員　三輪　正太郎

2023-07-11 12:39 UTC, dymmt commented
@Miwashotaro プルリクエストありがとうございます。

内容を確認して、developブランチに取り込むか判断します。
敬称、長い挨拶、署名はプルリクエストの確認・取り込み対応の結果に一切影響しません。
変更の内容のみを記載してください。

プルリクエストの聞き方の参考
- https://github.com/Tokyo-Metro-Gov/covid19/pull/7822

2023-07-11 12:56 UTC, dymmt commented
@Miwashotaro 
ハイパーリンクとして埋め込まれているURLが `iaeste.or.jp` 外になっています。
指摘した箇所以外も多々修正が必要な箇所があります。一度見直しと修正をお願いします。

https://github.com/iaeste-japan/www/pull/36/files

2023-07-11 12:57 UTC, dymmt requested changes

2023-07-11 12:57 UTC, dymmt commented on hugo/content/ja/information-session.md
> +| 1   | 2023年06月03日(土) 10:00-12:00 | 東大本郷キャンパス <br> (zoomでのハイブリッド)  |
@Miwashotaro 

1. Zoom Video Communications, Inc. 社のサービス名は `Zoom Meetings` です。
IAESTE Japanの公式webサイトに掲載する文面では、正しい商標で記載してください。
2. `東大本郷キャンパス <br> (zoomでのハイブリッド)` を `東京大学本郷キャンパス & Zoom Meetings (同時開催)` と記載してください

2023-07-11 12:57 UTC, dymmt commented on hugo/content/ja/information-session.md
> +- [説明会資料2023](https://github.com/iaeste-japan/www/blob/Miwashotaro-patch-1/hugo/static/files/internship/information-session/briefing-slides-2023%20(1).pdf)
@Miwashotaro 

1. ファイル名を `briefing-slides-2023%20(1).pdf` から `briefing-slides-2023-v20230711.pdf` に変更してください
1. ファイルへのURLがGitHubになっています。

https://github.com/iaeste-japan/www/blob/Miwashotaro-patch-1/hugo/static/files/internship/information-session/briefing-slides-2023%20(1).pdf


iaeste.or.jpドメインのURLに直すには以下のように修正してください。
```
[説明会資料2023](files/internship/information-session/briefing-slides-2023-v20230711.pdf)
```

2023-07-11 12:57 UTC, dymmt commented on hugo/content/ja/information-session.md
> +Twitterから参加申し込みを行ってください。
@Miwashotaro 
Twitter へのハイパーリンクを追加してください。Twitterのどのアカウントかわかりません。

2023-07-11 12:57 UTC, dymmt commented on hugo/content/ja/reports.md
> +| FY2022 | 生命機能科学 | ポルトガル | [PDF](https://github.com/iaeste-japan/www/blob/Miwashotaro-patch-1/hugo/static/files/internship/reports/training-report-fy2022-pt-nishijima.pdf) |
@Miwashotaro 

iaeste.or.jpドメインのURLに直すには以下のように修正してください。
```
[PDF](files/internship/reports/${ファイル名})
```

2023-07-11 12:57 UTC, dymmt commented on hugo/content/ja/required-docs.md
> +| [募集要項](https://github.com/iaeste-japan/www/blob/Miwashotaro-patch-1/hugo/static/files/internship/required-docs/application-guidelines-fy2024-ja-v20230720.pdf) | pdf | 2023/7/20 |
@Miwashotaro 

iaeste.or.jpドメインのURLに直すには以下のように修正してください。
```
[${ドキュメントの名称}](/files/internship/required-docs/${ファイル名})
```

2023-07-11 12:57 UTC, dymmt commented on hugo/content/ja/required-docs.md
> +| [Application Guidelines](https://github.com/iaeste-japan/www/blob/Miwashotaro-patch-1/hugo/static/files/internship/required-docs/application-guidelines-fy2024-en-v20230720.pdf) | pdf  | 2023/7/20 |
@Miwashotaro 

`https://github.com/iaeste-japan/www/blob/Miwashotaro-patch-1` と iaeste.or.jp ではないURLになっています。

iaeste.or.jpドメインのURLに直すには以下のように修正してください。

[${ドキュメントの名称}](/files/internship/required-docs/${ファイル名})

2023-07-11 12:57 UTC, dymmt commented on hugo/static/files/internship/information-session/briefing-slides-2023 (1).pdf
@Miwashotaro 
ファイル名を `briefing-slides-2023 (1).pdf` から `briefing-slides-2023-v20230711.pdf` に変更してください

2023-07-11 13:16 UTC, dymmt commented on hugo/static/files/internship/reports/training-report-fy2022-po-anonymous.pdf
@Miwashotaro 
ファイル名を `training-report-fy2022-po-anonymous.pdf` から `training-report-fy2022-pl-anonymous.pdf` に変更してください。

ポーランドの国コードは `pl` です。

https://iss.ndl.go.jp/help/help_ja/help_country_codes.html

2023-07-11 13:16 UTC, dymmt commented on hugo/static/files/internship/reports/training-report-fy2022-po-azuma.pdf
@Miwashotaro 
ファイル名を `training-report-fy2022-po-azuma.pdf` から `training-report-fy2022-pl-azuma.pdf` に変更してください。

ポーランドの国コードは pl です。

https://iss.ndl.go.jp/help/help_ja/help_country_codes.html

2023-07-11 13:16 UTC, dymmt commented on hugo/static/files/internship/required-docs/internship-dispatch-guidance-fy2024-ja-v20230720..pdf
@Miwashotaro 
ファイル名を `internship-dispatch-guidance-fy2024-ja-v20230720..pdf` から `internship-dispatch-guidance-fy2024-ja-v20230720.pdf` に変更してください

2023-07-12 07:13 UTC, Miwashotaro commented
ja/information-session.md
開催地に関する情報を東京大学本郷キャンパス & Zoom Meetings (同時開催)に変更しました。
添付ファイル名をbriefing-slides-2023-v20230711.pdfに変更し、iaeste.or.jpドメインのURLに直しました。
Twitterへのハイパーリンクを追加しました。
ja/reports.md
追加した研修報告書のURLをiaeste.or.jpドメインのURLに直しました。
2つのファイルの国コードを正しいものに変更しました。
ja/required-docs.md
追加したファイルのURLをiaeste.or.jpドメインのURLに直しました。
ファイルをinternship-dispatch-guidance-fy2024-ja-v20230720.pdfに変更しました。

2023-07-12 12:41 UTC, dymmt commented
> ja/information-session.md 開催地に関する情報を東京大学本郷キャンパス & Zoom Meetings (同時開催)に変更しました。 添付ファイル名をbriefing-slides-2023-v20230711.pdfに変更し、iaeste.or.jpドメインのURLに直しました。 Twitterへのハイパーリンクを追加しました。 ja/reports.md 追加した研修報告書のURLをiaeste.or.jpドメインのURLに直しました。 2つのファイルの国コードを正しいものに変更しました。 ja/required-docs.md 追加したファイルのURLをiaeste.or.jpドメインのURLに直しました。 ファイルをinternship-dispatch-guidance-fy2024-ja-v20230720.pdfに変更しました。

@Miwashotaro 

修正ありがとうございます。ただし、前後の行とずれた記載や変更前のMarkdownを参考にせず、誤った記載をしているようです。
次回からは変更前のMarkdownの内容や変更箇所の前後の記載をよく読んで、それに基づいて変更を行ってください。

プロジェクトの品質と一貫性を保つ上で非常に重要です。不適切な変更は他の編集者に影響を及ぼす可能性がありますので、注意を払ってください。

もし理解に困る箇所があれば、質問や疑問点がある場合は遠慮せずにお知らせください。
適切な変更を行うためにお手伝いします。

2023-07-14 03:10 UTC, Miwashotaro commented
ご指摘いただきありがとうございます。
ご指摘を受け、以下の点を再度修正しました。

　添付ファイルのリンクの記載方法を[ドキュメント名](/files/internship/reports/ファイル名)に統一しました。
　研修報告のページにある研修報告一覧表の派遣国名を正式名称に修正しました。
　information-sessionの説明会参加に関する記載に変更を加えました。

修正点は以上になります。
自分の力では上記の箇所しか修正点を見つけることができませんでした。
申し訳ないのですが、上記以外の修正点をご教示いただけますでしょうか。

2023-07-14 12:20 UTC, dymmt commented
@Miwashotaro 

> 自分の力では上記の箇所しか修正点を見つけることができませんでした。
申し訳ないのですが、上記以外の修正点をご教示いただけますでしょうか。

現時点で残ってる指摘箇所は以下のページで確認できます。
- https://github.com/iaeste-japan/www/pull/36/files 

引き続き修正対応、よろしくお願いします。

2023-07-24 03:07 UTC, Miwashotaro commented
information-session.md内の開催場所に関して修正を加えました。
how-it-works.md内の費用に関する文章は渡辺様からこのように変更してほしいと、変更指示書に記載して
あったので修正しませんでした。
残りの指摘箇所に関しては、何を修正すればいいのか判断が出来なかったので、
文章で教示していただけるとうれしいです。

2023-07-25 13:52 UTC, dymmt commented
> information-session.md内の開催場所に関して修正を加えました。 how-it-works.md内の費用に関する文章は渡辺様からこのように変更してほしいと、変更指示書に記載して あったので修正しませんでした。 残りの指摘箇所に関しては、何を修正すればいいのか判断が出来なかったので、 お手数をおかけしますが文章で教示していただけるとうれしいです。

@Miwashotaro 
プルリクエストへのコメントにどのように修正すればいいか全て文章で記載しています。
プルリクエストへのコメントを確認して、各コメントに対しての返信をお待ちしております。

[プルリクエストへのコメント](https://docs.github.com/ja/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/commenting-on-a-pull-request)

2023-07-25 14:40 UTC, dymmt commented
@Miwashotaro 

プルリクエストの分割を検討ください。
このプルリクエストには以下の内容が含まれています。

- 説明会の日程更新と資料の掲載
- IAESTE Japanへの納入額の補足事項追記
- 各種ドキュメント（2024年度版の募集要項、研修の手引き、申請書、派遣辞退届を日本語版、英語版）のアップロード
- エントリーフォームのドキュメント一覧から追加募集要項を削除しました。
- 募集要項、研修の手引き、申請書のファイルを2024年度版に更新
- 日本語版のドキュメント一覧で新たに派遣辞退届のファイルを追加
- 等々

一度に多くの変更をしているため、別々に更新できる内容が一部の修正に影響されて取り込みできません。
関連のあるトピック毎にプルリクエストを分割してを作成すれば、レビューが通ったプルリクエストから順に取り込むことができます。

2023-07-26 13:58 UTC, Miwashotaro commented
how it work.mdのIAESTE Japanへの納入額に関する文章の表現を変更しました。
ご提案ありがとうございます。プルリクエストの分割に関してですが、こちらにとっても
利点が多いのですが今回は時間の余裕がないので、このまま修正をお願いしたいです。
質問なのですが、iaeste.or.jpドメインのURLに直すためにファイルのリンクを
[説明会資料2023](files/internship/information-session/briefing-slides-2023-v20230711.pdf)
上記の形式に変更しましたが、プルリクエストのコメントによっては異なる形式で書くように指示されています。
iaeste.or.jpドメインのURLに直すためには、それぞれのコメントに従って修正を行うべきなのでしょうか。
それとも上記の形式で統一してよろしいでしょうか。
また、私が現在認識しているプルリクエストへのコメントの件数は10件ですが、
過去にイアエステの研修を行った方については、半分の金額となります。 また、オンライン研修を行った場合、半額が返金されます。の表記について、半額になるのは応募手数料、プログラム参加料のどれですか？誤解のないように、一意の意味になるように記載してください。
というコメントは確認出来ませんでした。
もし、このコメントを事前に出していた場合は、どこに出していたのか教えていただきたいです。
最後に申し訳ないのですが、どこの修正が解決したかわからなく不安を感じるので、プルリクエストへのコメントで指摘している問題点が解決されたときにコメントの下に表示されるresolve conversationを押していただけるとうれしいです。

2023-07-26 14:14 UTC, dymmt commented
@Miwashotaro 

Files changed のタブで、以下のスクリーンショットのように Show all changes を選択してみてください。
現在オープンしているコメントが見れると思います。
修正済みのコメント箇所は resolve conversation を押していますが、各コミットを選択すれば履歴として見れると思います。

![image](https://github.com/iaeste-japan/www/assets/114415867/ae6b79eb-e30a-4c9b-8b2b-f779c1adb273)

---

```
過去にイアエステの研修を行った方については、半分の金額となります。 また、オンライン研修を行った場合、半額が返金されます。の表記について、半額になるのは応募手数料、プログラム参加料のどれですか？誤解のないように、一意の意味になるように記載してください。
というコメントは確認出来ませんでした。
もし、このコメントを事前に出していた場合は、どこに出していたのか教えていただきたいです。
```

この辺りのURLでコメントが見えませんかね？
- https://github.com/iaeste-japan/www/pull/36/files/b5ae64583468b7dcb7003a90b23db1094df5a44f

2023-07-26 14:20 UTC, dymmt commented
@Miwashotaro 

> 質問なのですが、iaeste.or.jpドメインのURLに直すためにファイルのリンクを
説明会資料(files/internship/information-session/briefing-slides-2023-v20230711.pdf)
上記の形式に変更しましたが、プルリクエストのコメントによっては異なる形式で書くように指示されています。
iaeste.or.jpドメインのURLに直すためには、それぞれのコメントに従って修正を行うべきなのでしょうか。
それとも上記の形式で統一してよろしいでしょうか。

現状の以下のコードで問題ないと思います。過去に指摘したコメントを見ている気がしますね。
```
- [説明会資料2023](/files/internship/information-session/briefing-slides-2023-v20230712.pdf)
```

---

> また、私が現在認識しているプルリクエストへのコメントの件数は10件ですが、

現時点で対応してほしいコメントのスレッドは4つですね

2023-07-30 15:18 UTC, Miwashotaro commented
すみません、残っている4件のコメントのスレッドが確認出来ませんでした。
以下のURLでも確認出来ませんでした。
・https://github.com/iaeste-japan/www/pull/36/files/b5ae64583468b7dcb7003a90b23db1094df5a44f
申し訳ないのですが、再度conversationへの投稿をお願い出来ますでしょうか。

2023-08-01 13:26 UTC, dymmt commented
> すみません、残っている4件のコメントのスレッドが確認出来ませんでした。
以下のURLでも確認出来ませんでした。
・https://github.com/iaeste-japan/www/pull/36/files/b5ae64583468b7dcb7003a90b23db1094df5a44f
申し訳ないのですが、再度conversationへの投稿をお願い出来ますでしょうか。

@Miwashotaro 以下の対応をお願いします。

1. how-it-works.md
    https://github.com/iaeste-japan/www/blob/5c6da0aadf5c3b8ff94756eba2e7c14c9fc170b7/hugo/content/ja/how-it-works.md?plain=1#L52

    "イアエステ" は "IAESTE" と表記するよう、お願いします。

2. required-docs.md
    1. https://github.com/iaeste-japan/www/blob/5c6da0aadf5c3b8ff94756eba2e7c14c9fc170b7/hugo/content/ja/required-docs.md?plain=1#L27

        ファイル名は `pledge-ja-v20220816.docx` から変更していないので Update Date を変更しないでください。

        以下のように修正してください。
        ```
        | [誓約書](/files/internship/required-docs/pledge-ja-v20220816.docx) | docx | 2022/8/16 |
        ```

    2. https://github.com/iaeste-japan/www/blob/5c6da0aadf5c3b8ff94756eba2e7c14c9fc170b7/hugo/content/ja/required-docs.md?plain=1#L29

        `withdrawal-notice-ja-v2023.doc` のファイル名を `withdrawal-notice-ja-v20230720.doc` に変更してください。
        ファイル名を変更して再アップロードと、このハイパーリンクの修正をお願いします。


    3. https://github.com/iaeste-japan/www/blob/5c6da0aadf5c3b8ff94756eba2e7c14c9fc170b7/hugo/content/ja/required-docs.md?plain=1#L51

        ファイル名が `pledge-en-v20220816.docx` から変更されていません。なので Update Date は変更しないでください。

        以下のように修正してください。
        ```
        | [Pledge](/files/internship/required-docs/pledge-en-v20220816.docx) | docx | 2022/8/16 |
        ```

2023-08-02 14:03 UTC, Miwashotaro commented
how-it-works.mdにおいてイアエステの表記をIAESTEに変更しました。
2件のファイルのupdate dateを修正しました。
withdrawal-notice-ja-v2023.doc のファイル名を修正し、ハイパーリンクも併せて修正しました。

2023-08-02 14:11 UTC, dymmt commented
> how-it-works.mdにおいてイアエステの表記をIAESTEに変更しました。
2件のファイルのupdate dateを修正しました。
withdrawal-notice-ja-v2023.doc のファイル名を修正し、ハイパーリンクも併せて修正しました。

@Miwashotaro すべてのレビューが完了しました。動作確認としてdev環境に反映しました。
意図する変更になっているか、動作確認をお願いします。

以下のURLは 2023-08-03 02:00 までアクセスできます。
- https://iaestejapan--miwashotaro-patch-2023-1gm9zhqi.web.app

2023-08-03 07:39 UTC, Miwashotaro commented
動作確認が終わりました。
すべての修正箇所が意図したように機能していました。
本番環境への反映の方もよろしくお願いいたします。
今回の更新を支援していただきありがとうございました。

2023-08-06 04:18 UTC, merged